# Generated by Django 4.1.4 on 2023-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_groupchat_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='groupname',
            field=models.CharField(max_length=200),
        ),
    ]
