# Generated by Django 4.1.4 on 2023-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_alter_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
